require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '11.0'

production = ENV["XCODE_CONFIG"] == "Release"

target 'PrebuiltReact' do
  use_react_native!(
    :hermes_enabled => false,
    :fabric_enabled => false,
    :production => production,
  )

  # Manually add our third party pods
  pod 'react-native-safe-area-context', :path => "../node_modules/react-native-safe-area-context"
  pod 'RNGestureHandler', :path => "../node_modules/react-native-gesture-handler"


  unless production
    use_flipper!()
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end

